### ISSUE TITLE
tsc throws errors

### ISSUE THREAD

**Issue by nawafHinai** [microsoft/etcd3#107] opened 2019-09-15 11:21 UTC
when running tsc:
`node_modules/etcd3/lib/src/connection-pool.d.ts:16:98 - error TS2694: Namespace '"grpc"' has no exported member 'ChannelOptions'.

16     constructor(host: string, channelCredentials: grpc.ChannelCredentials, channelOptions?: grpc.ChannelOptions | undefined);
                                                                                                    ~~~~~~~~~~~~~~

node_modules/etcd3/lib/src/options.d.ts:2:10 - error TS2305: Module '"grpc"' has no exported member 'ChannelOptions'.

2 import { ChannelOptions } from 'grpc';
           ~~~~~~~~~~~~~~

node_modules/etcd3/lib/src/rpc.d.ts:15:43 - error TS2694: Namespace '"grpc"' has no exported member 'StatusMessage'.

15     on(event: 'status', fn: (status: grpc.StatusMessage) => void): this;
                                             ~~~~~~~~~~~~~


Found 3 errors.`

**Comment by jwalton** [comment] 2019-09-17 20:14
I think this is a dupe of https://github.com/mixer/etcd3/issues/54, but that's been open for a really long time.  :/

**Closed** 2020-06-17 03:45 UTC
